### ISSUE TITLE
Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.12.4:test

### ISSUE THREAD

**Issue by sparkybrit** [sethm/symon#1]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  2.167 s
[INFO] Finished at: 2021-09-10T02:39:45+01:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.12.4:test (default-test) on project symon: There are test failures.
[ERROR] 
[ERROR] Please refer to /Users/graeme/Downloads/symon-master/target/surefire-reports for the individual test results.
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

first exception is 
changeCursorStartLineShouldTriggerCallback(com.loomcom.symon.CrtcTest)

% ls -la `which mvn`
lrwxr-xr-x  1 gharker  admin  29 10 Sep 02:24 /usr/local/bin/mvn -> ../Cellar/maven/3.8.2/bin/mvn

% mvn -v
Apache Maven 3.8.2 (ea98e05a04480131370aa0c110b8c54cf726c06f)
Maven home: /usr/local/Cellar/maven/3.8.2/libexec
Java version: 16.0.2, vendor: Homebrew, runtime: /usr/local/Cellar/openjdk/16.0.2/libexec/openjdk.jdk/Contents/Home
Default locale: en_GB, platform encoding: UTF-8
OS name: "mac os x", version: "10.15.7", arch: "x86_64", family: "mac"
%

**Comment by sethm** [comment]
I think I've fixed this with my latest push, please give it a try. Mockito 1 was no longer compatible with Java 16, so I've updated to Mockito 3.

**Comment by sparkybrit** [comment]
Great! This one is fixed.
