### ISSUE TITLE
Default rom.bin not working?

### ISSUE THREAD

**Issue by DualBrain** [sethm/symon#11]
I followed the instructions for getting EhBASIC working and after a while noticed that nothing seemed to be working. I then looked at the memory map and everything was blank.

- copy ehbasic.rom to same folder as .jar; renaming it to rom.bin.
- double click on .jar (on Windows 11 if that matters)...

Memory blocks are empty, no error message, no indication that anything was loaded.

I then attempted to start the .jar using command line `java -jar symon-1.3.2.jar` and got the following error:

`[main] INFO com.loomcom.symon.machines.SymonMachine - No ROM file specified, loading empty R/W memory image`

Starting it by appending `-rom rom.bin`... things working as expected.

(BTW, THANK YOU!!!! I've spent the past several hours trying to get a copy of EhBASIC up and running so I can experiment with it for https://gotbasic.com and thanks to your efforts, SUCCESS!)

**Comment by sethm** [comment]
Oops! You're right, that feature no longer exists. I've just updated the main README file and the README file in the `samples` directory to clarify how ROM images can be loaded. Sorry for the confusion!

**Comment by sethm** [comment]
I forgot to ask: Does this solve your issue? I don't plan on bringing back the behavior of automatically loading any file named `rom.bin` in the current working directory, so I hope that the documentation is clearer now.

If this has solved your problem, can you close this issue? Thank you!

**Comment by DualBrain** [comment]
Yes, addresses the issue. Thanks.
