### ISSUE TITLE
Backspace key not deleting

### ISSUE THREAD

**Issue by chelsea6502** [sethm/symon#13]
Hello!

I've run into an issue while trying to use the serial terminal with the ACIA 6551 emulator. Transmitting the delete character (0x7F) successfully deletes the last character sent, but seems the backspace character (0x08) doesn't do the same. It just makes an empty space. I don't have the same problem on real hardware.

<img width="215" alt="image" src="https://github.com/sethm/symon/assets/122856043/177fe78e-5823-43ad-825a-065b0faa4a82">

Is that by design, or is it an issue? It may be a problem with my own code, so let me know if you can't replicate it.

**Comment by sethm** [comment]
Yeah, I would classify this as a bug. Hitting BACKSPACE actually deletes the last character pressed in BASIC (at least in EhBASIC), but moves the cursor forward. I just pushed a change to the master branch that should address this. Let me know if it fixes things for you!

**Comment by chelsea6502** [comment]
<img width="222" alt="image" src="https://github.com/sethm/symon/assets/122856043/3cf70549-5847-404f-90a7-f88d47dad3c0">

That did the trick. Thank you so much! Now I have a solid test environment for serial IO.
