### ISSUE TITLE
Feature request: Command line flag to disable halt on BRK

### ISSUE THREAD

**Issue by chelsea6502** [sethm/symon#14]
Hello again!

BBC BASIC processes a command by calling BRK after typing a command and pressing enter.

This means that by default, Symon halts every time I send a new command. At every start, I have to disable it manually in the settings.

What would make things quicker and easier for me is a command line flag (perhaps "--no-halt" / "-nh"?) that would disable the halt on break at the very start.

**Comment by sethm** [comment]
This should be a pretty easy change, I'll try to get it in this week.

**Comment by chelsea6502** [comment]
Awesome. Thanks!!

**Comment by sethm** [comment]
I've just pushed a fix that makes "Halt on `BRK`" no longer true by default. You can now turn it on by passing a `-b` flag at startup, and of course, as before, you can toggle it at runtime, but it felt like the best course of action to not have it set by default!

Please give the latest changes a try and let me know if they work for you.

**Comment by chelsea6502** [comment]
Fantastic! Works perfectly for me. Thank you!
