### ISSUE TITLE
IRQs set BRK flag, BRK's should also be non-maskable

### ISSUE THREAD

**Issue by LIV2** [sethm/symon#14]
Hi, 

I noticed a while back that whenever any kind of IRQ is triggered, the BRK flag is set regardless of whether it was a BRK or not.

Also, BRK is not maskable: http://www.atarimax.com/jindroush.atari.org/aopc.html#BRK

Here's how I fixed it: https://github.com/LIV2/symon/commit/8335cf5421f7171682342e065cf5229403a6967b
It's probably a crappy way to fix this issue but I'm not really a programmer.

**Comment by ccureau** [comment]
Hi Matt,

I'm not sure where Seth is, but nice catch on the BRK.

There are quite a few bugs in the NMOS versions of the 65xx CPUs... In fact
I learned about a new one while researching this issue you've solved.

If we don't hear from him, I'll pull into master.

Cheers,
Chris

**Comment by LIV2** [comment]
Cool, I noticed I left in a comment that doesn't make sense with my changes so I'll update it and let you know once I've done so

**Comment by ccureau** [comment]
Sounds good...I'll commit when I see your message.

**Comment by LIV2** [comment]
I've updated now and created a pull request: https://github.com/sethm/symon/pull/15

**Comment by LIV2** [comment]
Closing as the change was merged
