### ISSUE TITLE
Memory Window resets ACIA status register

### ISSUE THREAD

**Issue by izuannazrin** [sethm/symon#16]
While writing a driver for 6551 ACIA, I noticed the code won't work with Memory Window opened. After examining the code, I found out that when Memory Window calls read(), ACIA resets its status register.

```
/* MemoryWindow.java */
public Object getValueAt(int row, int column) {
    try {
        if (column == 0) {
            return Utils.wordToHex(fullAddress(row, 1));
        } else if (column < 9) {
            // Display hex value of the data
            return Utils.byteToHex(bus.read(fullAddress(row, column)));
        } else {
            // Display the ASCII equivalent (if printable)
            return Utils.byteToAscii(bus.read(fullAddress(row, column - 8)));
        }
    } catch (MemoryAccessException ex) {
        return "??";
    }
}

/* Acia6551.java */
public int read(int address) throws MemoryAccessException {
    switch (address) {
        case DATA_REG:
            return rxRead();
        case STAT_REG:
            return statusReg();
        case CMND_REG:
            return commandRegister;
        case CTRL_REG:
            return controlRegister;
        default:
            throw new MemoryAccessException("No register.");
    }
}

/* Acia.java */
public synchronized int rxRead() {
    lastRxRead = System.nanoTime();
    overrun = false;
    rxFull = false;
    return rxChar;
}
```

This can be prevented by adding additional argument to device's read() to differentiate CPU's memory access and Memory Window's memory access. For example, the fixed code will look like this:

```
/* MemoryWindow.java */
public Object getValueAt(int row, int column) {
    try {
        if (column == 0) {
            return Utils.wordToHex(fullAddress(row, 1));
        } else if (column < 9) {
            // Display hex value of the data
            return Utils.byteToHex(bus.read(false, fullAddress(row, column)));
        } else {
            // Display the ASCII equivalent (if printable)
            return Utils.byteToAscii(bus.read(false, fullAddress(row, column - 8)));
        }
    } catch (MemoryAccessException ex) {
        return "??";
    }
}

/* Acia6551.java */
public int read(boolean cpuAccess, int address) throws MemoryAccessException {
    switch (address) {
        case DATA_REG:
            return rxRead(cpuAccess);
        case STAT_REG:
            return statusReg(cpuAccess);
        case CMND_REG:
            return commandRegister;
        case CTRL_REG:
            return controlRegister;
        default:
            throw new MemoryAccessException("No register.");
    }
}

/* Acia.java */
public synchronized int rxRead(boolean cpuAccess) {
    if (cpuAccess) {
        lastRxRead = System.nanoTime();
        overrun = false;
        rxFull = false;
    }
    return rxChar;
}
```

(After this, ACIA interrupt bit can be easily implemented)

**Comment by LIV2** [comment]
I'm not 100% sure but would we also need to add the cpuAccess bool to every other instance of read() from other devices/ram/rom regions etc?

Hopefully @sethm pops by soon to answer this issue, I'd like to see interrupt support for the ACIA too

**Comment by izuannazrin** [comment]
Unfortunately yes. Maybe there are some kind of optional argument in Java? (I don't know much about Java)

**Comment by ccureau** [comment]
This solution feels right.  I think it might have to be expanded out into
other devices that generate interrupts.

Seth hasn't been very active in a while...I was actually trying to do
interrupts with the ACIA as well.

**Comment by sethm** [comment]
Hi guys! Sorry for the delay in joining this thread, life at my day job has been incredibly hectic, and I've been devoting a lot of my free time to a new AT&T 3B2 emulator I'm working on.

I think you're right that we need a flag to indicate whether the access is from the cpu or not. I had to do something very similar in the 3B2 emulator.

If you'd like to submit a pull request, I'd be happy to merge it.

**Comment by LIV2** [comment]
Cool thanks @sethm, I've been following the 3B2 stuff on twitter and it looks like fun

I'm working on a Pull request right now, cheers

**Comment by LIV2** [comment]
Created pull #17
