### ISSUE TITLE
BUILD FAILURE: An API incompatibility was encountered

### ISSUE THREAD

**Issue by sparkybrit** [sethm/symon#2]
% mvn package
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  8.373 s
[INFO] Finished at: 2021-09-25T06:51:32+01:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-jar-plugin:2.6:jar (default-jar) on project symon: Execution default-jar of goal org.apache.maven.plugins:maven-jar-plugin:2.6:jar failed: An API incompatibility was encountered while executing org.apache.maven.plugins:maven-jar-plugin:2.6:jar: java.lang.ExceptionInInitializerError: null

% mvn -v
Apache Maven 3.8.2 (ea98e05a04480131370aa0c110b8c54cf726c06f)
Maven home: /usr/local/Cellar/maven/3.8.2/libexec
Java version: 17, vendor: Homebrew, runtime: /usr/local/Cellar/openjdk/17/libexec/openjdk.jdk/Contents/Home
Default locale: en_GB, platform encoding: UTF-8
OS name: "mac os x", version: "10.15.7", arch: "x86_64", family: "mac"

**Comment by sethm** [comment]
Hmm, I can't reproduce this one, but I'll try updating the maven JAR plugin to see if that helps.

**Comment by sethm** [comment]
I've pushed a change that might take care of this. I upgraded `maven-jar-plugin` from 2.6 to 3.2.0, and changed from using `maven-assembly-plugin` to `maven-shade-plugin` for final packaging of the JAR with dependencies.

**Comment by sparkybrit** [comment]
BUILD SUCCESS
