### ISSUE TITLE
Top menus dont work on gentoo

### ISSUE THREAD

**Issue by z3roco01** [sethm/symon#3]
I'm on fully up to date gentoo using openjdk and the top options File, View, Simulator don't work. When i try to click them there only open while I'm clicking and i can't click anything in it

**Comment by sethm** [comment]
Hello, can you please tell me which version of OpenJDK you're using? You can find out by typing `java -version`

**Comment by z3roco01** [comment]
output is 
```
openjdk version "1.8.0_302"
OpenJDK Runtime Environment (Temurin)(build 1.8.0_302-b08)
OpenJDK 64-Bit Server VM (Temurin)(build 25.302-b08, mixed mode)
```
but i tried also tried with 17 its `-version` output is 
```
java version "17.0.1" 2021-10-19 LTS
Java(TM) SE Runtime Environment (build 17.0.1+12-LTS-39)
Java HotSpot(TM) 64-Bit Server VM (build 17.0.1+12-LTS-39, mixed mode, sharing)
```

**Comment by sethm** [comment]
One more question: What desktop environment are you using?

**Comment by z3roco01** [comment]
im using dwm

**Comment by sethm** [comment]
OK, I did a little more research and apparently this is a known issue with dwm. I'm not sure there's anything I can do about it, but I'll keep looking. You can try a workaround posted here, and see if that helps in the meantime (this is Arch, but apparently applies to Gentoo as well:

https://wiki.archlinux.org/title/Java#Gray_window,_applications_not_resizing_with_WM,_menus_immediately_closing

https://bbs.archlinux.org/viewtopic.php?id=266137

**Comment by z3roco01** [comment]
sorry i forgot about this but doing `export _JAVA_AWT_WM_NONREPARENTING=1` fixed it
