### ISSUE TITLE
jar

### ISSUE THREAD

**Issue by Franck78** [sethm/symon#4]
Hello,

I was searching for a 6502 tool to try to debug understand an old pcb poker game machine.

Sadly I give up on your prog. Strictly zero interest in installing or building any java things (mvn ????).

I just need "java -jar 6502emu.jar"  !!!!!

Just publish the jar file.

Thank you

**Comment by sethm** [comment]
Hello,

The JAR file is now available on the releases page.

**Comment by Franck78** [comment]
Cool, thank you for the quick reaction ;)
